### PR TITLE
migrate ChartsRealmDemo and bugfix

### PR DESCRIPTION
**Pull request by liuxuan30**
1. upgrade ChartsRealmDemo to swift 4
2. fix `CGAffineTransformInvert: singular matrix` warning. data setter and zoom() order is reversed

### CODE REVIEW

**Comment by liuxuan30** [comment]
@petester42 I don't see Xcode warns me about @objc use when `SWIFT_SWIFT3_OBJC_INFERENCE` is `on`, and it works as usual without any warning throw out at run time. Does this mean we don't have to add @objc for classes such as `BalloonMarker`, `XYMarkerView`, `RadarMarkerView`, `LargeValueFormatter`, which are the only swift classes?

**Comment by pmairoldi** [comment]
The problem I had was that when using the new “minimize interface” that the objective-c code didn’t get acess to all the properties it needed. If you able to make stuff work without it go ahead.

**Comment by liuxuan30** [comment]
I'm not sure neither, as Xcode have no complain and works as usual.I clicked every realm demo chart and no crash at all. It seems all demo charts don't use marker at all. So @objc is not a must?

**Comment by pmairoldi** [comment]
If it works then whatever. We can revisit it if it stops working.

**Comment by pmairoldi** [comment]
Merge whenever you’re ready.

**Pull request merged**
